env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "react/jsx-filename-extension": [ "warn", {"extensions": [".tsx"]} ],
  "import/extensions": ["error", "ignorePackages", {"ts": "never", "tsx": "never"}],
  "@typescript-eslint/explicit-function-return-type": ["error", {"allowExpressions": true}],
  "max-len": ["error", { "code": 120 }],
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}],
  "semi": ["error", "never"],
  "quotes": ["error", "double"]
}
settings: {
  "import/resolver": {
    "typescript": {}
  }
}
